name: server
on:
  push:
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: |
          cd server
          go build -ldflags "-s -w" -o main -v main.go

      - name: Deploy to server
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          mkdir -p $HOME/.ssh/
          echo "$SERVER_SSH_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan $REMOTE_HOST >> $HOME/.ssh/known_hosts
          cd server
          ssh $REMOTE_USER@$REMOTE_HOST "service game-log stop"
          scp main $REMOTE_USER@$REMOTE_HOST:$REMOTE_TARGET
          ssh $REMOTE_USER@$REMOTE_HOST "service game-log start && service game-log status"